# ワークフロー
name: ServerDeploy

# イベント
on:
  # GitHubにプッシュされた時
  push:
    branches: [ main ]
  # GitHubでプルリクエストが作られた時
  pull_request:
    branches: [ main ]
  # 手動実行
  workflow_dispatch:

# ジョブ
jobs:
  # ジョブ名
  deploy:
    # ランナー
    runs-on: ubuntu-latest

    # ステップ
    steps:
      # アクション1。リポジトリのソースをチェックアウトする
      - name: git checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      # アクション2。サーバーデプロイ
      - name: deploy
        uses: easingthemes/ssh-deploy@9ab39935552e9fe6706e9c9bf2a70a3328a4a5e6
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}  # サーバーの秘密鍵
            ARGS: "-rltgoDzvO"                              # rsyncのオプション
            SOURCE: theme                                   # アップロードするディレクトリ
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}         # アップロード先のサーバーホスト
            REMOTE_USER: ${{ secrets.REMOTE_USER }}         # アップロード先のサーバーユーザ
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}         # アップロード先のサーバーポート
            TARGET: ${{ secrets.REMOTE_TARGET }}            # アップロード先のサーバーディレクトリ
